"""Export only aggregate research data for the static project page (stdlib only).

Run from the project root:
    python3 docs/scripts/export_data.py --research-root /path/to/basellm-tts
No prompts, trajectories, task identifiers, or machine paths are exported.
"""
import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path

MODELS = ["gemma-4-31B", "Qwen2.5-32B", "Qwen3.5-35B-A3B", "Ministral-3-14B"]
INVENTORY = "results/summary/260824-0010_scalability_inventory_4fam_scope.json"


def read_counts(root, cell):
    # The source figure cache stores (successes, trials), keyed by source path,
    # modification time and byte count. Verify the latter before trusting it.
    counts = []
    sources = []
    for name in cell["paths"]:
        source = Path(name)
        if not source.exists() and "/results/" in name:
            source = root / "results" / name.split("/results/", 1)[1]
        stat = source.stat()
        matches = list((root / "results/summary/cache").glob(
            f"*{source.name}__{int(stat.st_mtime)}_{stat.st_size}.json"))
        if matches:
            raw = matches[0].read_bytes()
            counts.extend(json.loads(raw))
            sources.append({"file": source.name, "count_cache_sha256": hashlib.sha256(raw).hexdigest()})
        else:
            with source.open() as stream:
                for line in stream:
                    item = json.loads(line)
                    flags = item["pass_flags"]
                    counts.append([sum(flags), len(flags)])
            sources.append({"file": source.name})
    assert len(counts) == cell["n_tasks"], (cell["pair"], cell["dataset"], len(counts))
    assert all(n == 128 and 0 <= c <= n for c, n in counts)
    return counts, sources


def aggregate(counts):
    histogram = Counter(c for c, _ in counts)
    curve = []
    for k in range(1, 129):
        value = 0
        for c, frequency in histogram.items():
            fail = 1.0
            for j in range(k):
                fail *= max(0, 128 - c - j) / (128 - j)
            value += frequency * (1 - fail)
        curve.append(round(value / len(counts), 10))
    n = len(counts)
    return {"tasks": n, "curve": curve,
            "histogram": [histogram[c] for c in range(129)],
            "categories": [histogram[0] / n, (n - histogram[0] - histogram[128]) / n, histogram[128] / n]}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--research-root", type=Path, required=True)
    args = parser.parse_args()
    inventory = json.loads((args.research_root / INVENTORY).read_text())
    data = {"rollouts": 128, "models": MODELS, "cells": {}}
    provenance = {"inventory": Path(INVENTORY).name, "sources": {}}
    for cell in inventory["cells"]:
        if cell["pair"] not in MODELS or cell["dataset"] not in ["webshop", "bfcl", "acebench"]:
            continue
        if cell["dataset"] == "acebench" and cell["split"] != "noser14":
            continue
        key = cell["pair"] + "/" + cell["dataset"]
        arm = "post" if cell["arm"] == "rl" else "base"
        counts, sources = read_counts(args.research_root, cell)
        data["cells"].setdefault(key, {})[arm] = aggregate(counts)
        provenance["sources"][key + "/" + arm] = sources
    assert len(data["cells"]) == 12
    assert all(set(v) == {"base", "post"} for v in data["cells"].values())
    check = data["cells"]["gemma-4-31B/webshop"]
    assert check["base"]["categories"] == [.124, .876, 0]
    assert check["post"]["categories"] == [.44, .30, .26]
    out = Path(__file__).resolve().parents[1] / "assets"
    out.mkdir(parents=True, exist_ok=True)
    (out / "research-data.js").write_text("// Generated by scripts/export_data.py; do not edit.\nwindow.RESEARCH_DATA = " + json.dumps(data, separators=(",", ":")) + ";\n")
    (out / "data-provenance.json").write_text(json.dumps(provenance, indent=2) + "\n")
    print(f"Exported {len(data['cells'])} model/benchmark pairs, 128 budgets each.")


if __name__ == "__main__":
    main()
